# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul_16_32/mul_16_32.xci
# IP: The module: 'mul_16_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul_16_32/mul_16_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_16_32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul_16_32/mul_16_32.xci
# IP: The module: 'mul_16_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul_16_32/mul_16_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_16_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
