//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/02/23 00:00:00
//----------------------------------------------------------------------------------------------------
#include <string.h>
#include "nnnet.h"
NNNET* nnn_init(void);
int nnn_load_weight(NNNET* np);
int nnn_run(NNNET* np, void *dp);
