//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/02/25 00:00:00
//----------------------------------------------------------------------------------------------------
#include <string.h>
#include <assert.h>
#include "nnnet.h"
NNNET* nnn_init(void);
int nnn_load_weight_from_files(NNNET* np, const char *path);
int nnn_run(NNNET* np, void *dp);
