# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/mul17_16/mul17_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul17_16 || ORIG_REF_NAME==mul17_16}]
