# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xcku035-fbva676-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.cache/wt [current_project]
set_property parent.project_path /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul8_16/mul8_16.dcp
set_property used_in_implementation false [get_files /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul8_16/mul8_16.dcp]
add_files -quiet /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul8_8/mul8_8.dcp
set_property used_in_implementation false [get_files /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul8_8/mul8_8.dcp]
add_files -quiet /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul16_16/mul16_16.dcp
set_property used_in_implementation false [get_files /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul16_16/mul16_16.dcp]
read_verilog -library xil_defaultlib {
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/q_add8.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/q_mul_core8.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/q_inv8.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/q_mul8.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/M0.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/local_mem.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/lmcnt.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/cpu_if.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/npu_core.v
  /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/src/npu8_top.v
}
read_ip -quiet /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul17_16/mul17_16.xci
set_property used_in_implementation false [get_files -all /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul17_16/mul17_16_ooc.xdc]
set_property is_locked true [get_files /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul17_16/mul17_16.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top npu8_top -part xcku035-fbva676-3-e


write_checkpoint -force -noxdef npu8_top.dcp

catch { report_utilization -file npu8_top_utilization_synth.rpt -pb npu8_top_utilization_synth.pb }
