import os
import datetime
import keras
# いろいろいったん決め打ちで

input_model = '/home/natu/myproj/NPU/example/keres_cnn/keras/output/cnn.json'
output_dir = '/home/natu/myproj/NPU/example/keres_cnn/c_ref/nnn_gen'

output_cfile = 'nnn_gen.c'
output_hfile = 'nnn_gen.h'


def generate_header_file(file):
    with open(file, 'w') as fp:
        write_file_header(fp)
        fp.write('#include "nnnet.h"\n')
        fp.write('NNNET* nnn_init(void);\n')


def generate_c_file(file):
    with open(file, 'w') as fp:
        write_file_header(fp)
        # 将来的にはstaticにしてファイル内にシンボルを隠蔽
        fp.write('// network\n')
        fp.write('NNNET g_nnn;\n')
        fp.write('\n')
        fp.write('// layers\n')


def write_file_header(fp):
    today = datetime.date.today()

    fp.write("//----------------------------------------------------------------------------------------------------\n")
    fp.write("// This file is automatically generated.\n")
    fp.write("// %s\n" % today.strftime('%Y/%m/%d %H:%M:%S'))
    fp.write("//----------------------------------------------------------------------------------------------------\n")

json_string = open(input_model).read()
model = keras.models.model_from_json(json_string)

print(model.summary())

generate_header_file(os.path.join(output_dir, output_hfile))
generate_c_file(os.path.join(output_dir, output_cfile))
