# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul8_8/mul8_8.xci
# IP: The module: 'mul8_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul8_8/mul8_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul8_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul8_8/mul8_8.xci
# IP: The module: 'mul8_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/natu/data/proj/myproj/NPU/fpga_implement/npu8/npu8.srcs/sources_1/ip/mul8_8/mul8_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul8_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
