//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/03/09 00:00:00
//----------------------------------------------------------------------------------------------------
#include <assert.h>
#include "nnnet.h"
#include "nnnet_def.h"
int convolution2d3x3_iui8_of(NNNET_LAYER *np, void *inp, void *outp);
int convolution2d3x3_if_of(NNNET_LAYER *np, void *inp, void *outp);
